CREATE TABLE `Papel` (
  `ID` INT(5) UNSIGNED NOT NULL AUTO_INCREMENT,
  `TIPO` varchar(1) NOT NULL,
  `DESCRICAO` varchar(100) NOT NULL,
  `OBSERVACAO` varchar(100) NOT NULL,
 
  PRIMARY KEY (`ID`)
) ENGINE=MyISAM DEFAULT CHARSET=latin1;



INSERT INTO `papel`(`TIPO`, `DESCRICAO`, `OBSERVACAO`) VALUES ('B','BIBLIOTECARIO','PAPEL PARA PERMISSÃO DE CADASTROS GERAIS E DE ATENDENTES.');
INSERT INTO `papel`(`TIPO`, `DESCRICAO`, `OBSERVACAO`) VALUES ('A','ATENDENTE','CADASTRO DE ATENDENTE DA BIBIOTECA.');
INSERT INTO `papel`(`TIPO`, `DESCRICAO`, `OBSERVACAO`) VALUES ('U','USUARIO','CADASTRO DE USUARIO DA BIBLIOTECA.');
INSERT INTO `papel`(`TIPO`, `DESCRICAO`, `OBSERVACAO`) VALUES ('O','OUTRO','CADASTRO DE OUTROS TIPOS DE PESSOAS.');